### ISSUE TITLE
Dynamic "Edit on GitHub" button

### ISSUE THREAD

**Issue by ravimakhija** [datascijedi/website#25]
It would be nice to have a page-specific "Edit on GitHub" button on the website. Since we do not currently use the `toc` feature on the website, the built-in Quarto method for this functionality does not work. 

A few workaround ideas are:

1) Use a blank table of contents. Perhaps position the table of contents at the bottom of the website body. (Downside: would probably have to remember to add some code whenever markdown sections are used. Also, might not be possible to put in the footer.)
2) Use document-specific variables to grab the name of the source document and use this to make a link to the appropriate page on GitHub manually. (Downside: I don't think such variables exist, so we would have to define them for each source document, or find a way to automate that.)
3) Look into using a Quarto shortcode/extension that is able to dynamically get the source file name, and use that to manually generate the page-specific GitHub links. 
4) Use the first option, but in addition consider JS/CSS-based solutions to change the position of the blank Table of Contents in the footer. 

This issue picks up from where #16 left off. fyi @mine-cetinkaya-rundel @fatso-jetson

**Comment by fatso-jetson** [comment]
@ravimakhija I have a thought. In HTML, is there a way to autocreate URLs so that you don't have to specify the page name, it is automatically added when the page is rendered? A self-reference, essentially.

My thinking is that, if there is, we could setup an HTML file with, e.g.:

`<a href="https://github.com/realworlddatascience/realworlddatascience.github.io/edit/main/{......}">Edit on GitHub</a></p>`

where the `{......}` is the page file name (Activities.qmd, etc.).

Then, in the site _quarto.yml file, we use the `include-after-body:` option for this to be added to each page, with each URL customised for each page automatically.

**Comment by ravimakhija** [comment]
I am not aware of any HTML-only way to do that.  However using client-side JavaScript it might be possible to use `document.location` to form the link dynamically and then insert into the website. So, that's another potential option to consider.

**Comment by ravimakhija** [comment]
Closed with MR #26.
