### ISSUE TITLE
Navbar sizing issue

### ISSUE THREAD

**Issue by fatso-jetson** [datascijedi/website#30]
Navbar changes size and spacing depending on page selection. Home and JEDI Corner are one size, all other pages are a different size. 

Unsure of the cause of this. Could be because Home and JEDI Corner are primarily listing pages - maybe this affects the design defaults somehow?

**Comment by fatso-jetson** [comment]
I've fixed the size and spacing around the navbar logo and website title in 31a2575, so this is now consistent across the site.

The navbar still seems to increase in height a fraction on the Home and JEDI Corner pages relative to other pages. Can't figure out the cause of this.

**Comment by ravimakhija** [comment]
It seems that a `<style>` tag is inserted when a listing is used that sets a `margin-top` and `margin-bottom`, and this seems to make the JEDI Corner nav height deviate from the others. I've added a potential fix in PR #81 for this, taking the approach of hard coding the nav height. 

Regarding the fix on the spacing around the navbar logo, it appears to me that the navbar logo moves upward slightly on the home page. I'm not sure if this minor formatting issue was present back when this issue was already opened up though.

**Comment by ravimakhija** [comment]
The changing nav height issue as well as the navbar logo moving upward issue should be addressed in the new fix provided in PR #82, which supersedes PR #81.

**Comment by ravimakhija** [comment]
As it turns out, there was an even simpler fix: scoping the `<style>` element from `jedi-corner.yml` to a list item, so that it does not affect the nav image and cause the nav to increase in height. 

The new fix was pushed via PR #83.
