### ISSUE TITLE
Fix for webinar listings page size/positioning

### ISSUE THREAD

**Issue by brtarran** [datascijedi/website#31]
@ravimakhija flagged that Webinar page used to shift to the right relative to other pages in the Activities section. I believe this is caused by the absence of a Table of Contents being active on this page - when TOC is set to True, page positioning is in keeping with other pages in section.

Have implemented temporary fix, setting page-layout to "full", but this means that Webinar page width is now greater than all other site pages.

**Comment by ravimakhija** [comment]
This does seem to fix the shifting of the Webinars page from what I see. 

Do you think there are any downsides, practical or otherwise, regarding the "page width" of the Webinar page being greater than all other sites? I can't see any issue from my side, but perhaps different clients (e.g. larger monitors) may behave differently.

**Comment by fatso-jetson** [comment]
I think the downsides are only aesthetic. The page width is fully responsive, so all content displays regardless of screen size.

**Comment by ravicodelabs** [comment]
Your fix of setting `page-layout: full` for `webinars.qmd` looks good to me!

**Comment by ravicodelabs** [comment]
Heard with @yates and workarounds are working fine, so closing this issue.
